# Generated by Django 4.2.3 on 2023-10-19 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0002_userprofile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='profile_pics/default.jpg', upload_to='profile_pics'),
        ),
    ]
