# Generated by Django 4.2.3 on 2023-10-20 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0003_question_pub_date_alter_userprofile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
