# Generated by Django 4.2.3 on 2023-10-24 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0004_answer_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
